{% set name = "dependabot-cli" %}
{% set version = "1.64.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dependabot/cli/archive/v{{ version }}.tar.gz
  sha256: c6dc6564636b01ab90e24315e37213253d43d5f91fc960e2d66791d29641730c

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - dependabot --help

about:
  home: https://github.com/dependabot/cli
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A tool for testing and debugging Dependabot update jobs.
  dev_url: https://github.com/dependabot/cli

extra:
  recipe-maintainers:
    - danielnachun
