{% set name = "dependabot-cli" %}
{% set version = "1.69.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dependabot/cli/archive/v{{ version }}.tar.gz
  sha256: 9940cd0d513d623b5708b070cabfcc1caf5afdb173b918ebafcf50a9f9069ad1

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - dependabot --help

about:
  home: https://github.com/dependabot/cli
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A tool for testing and debugging Dependabot update jobs.
  dev_url: https://github.com/dependabot/cli

extra:
  recipe-maintainers:
    - danielnachun
