{% set name = "dependabot-cli" %}
{% set version = "1.56.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dependabot/cli/archive/v{{ version }}.tar.gz
  sha256: be6793ae0c099fc3fafef37b6b2ee9c69f8ecce6a5f5f8f4bda31780a6560374

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - dependabot --help

about:
  home: https://github.com/dependabot/cli
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A tool for testing and debugging Dependabot update jobs.
  dev_url: https://github.com/dependabot/cli

extra:
  recipe-maintainers:
    - danielnachun
