{% set name = "dependabot-cli" %}
{% set version = "1.60.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dependabot/cli/archive/v{{ version }}.tar.gz
  sha256: 1e5fd1f5ce77d8cfca9978e9993ec14164e763cf92016101e1d67a409e05d638

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - dependabot --help

about:
  home: https://github.com/dependabot/cli
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A tool for testing and debugging Dependabot update jobs.
  dev_url: https://github.com/dependabot/cli

extra:
  recipe-maintainers:
    - danielnachun
