schema_version: 1

context:
  version: "1.81.0"

package:
  name: dependabot-cli
  version: ${{ version }}

source:
  url: https://github.com/dependabot/cli/archive/v${{ version }}.tar.gz
  sha256: 0ebd3ee1be5f17ffdc9873899f6606bd287efcc9a6ce1a954450c2cc3d8f3205

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - dependabot --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A tool for testing and debugging Dependabot update jobs.
  homepage: https://github.com/dependabot/cli
  repository: https://github.com/dependabot/cli

extra:
  recipe-maintainers:
    - danielnachun
