schema_version: 1

context:
  version: "1.82.0"

package:
  name: dependabot-cli
  version: ${{ version }}

source:
  url: https://github.com/dependabot/cli/archive/v${{ version }}.tar.gz
  sha256: 78724bf99e251ed80ae527304a2ee697e9b2116d67ba7538a41d6bf7b23cee7a

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - dependabot --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A tool for testing and debugging Dependabot update jobs.
  homepage: https://github.com/dependabot/cli
  repository: https://github.com/dependabot/cli

extra:
  recipe-maintainers:
    - danielnachun
